#include "ControladorWeb.h"

ControladorWeb::ControladorWeb()=default;

String ControladorWeb::getWebApp(){
    String app = 
    "<!DOCTYPE html>\n"
        "<html lang=\"es\">\n"
        "<head>\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\n"
        "    <style>\n"
        "        body {\n"
        "            padding: 20px;\n"
        "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
        "            background-color: #f0f0f0;\n"
        "            color: #333;\n"
        "            text-align: center;\n"
        "        }\n"
        "        h1 {\n"
        "            color: #1a73e8;\n"
        "            font-size: 36px;\n"
        "            margin-bottom: 30px;\n"
        "        }\n"
        "        #mainTable {\n"
        "            width: 100%;\n"
        "            max-width: 400px;\n"
        "            margin: auto;\n"
        "            table-layout: fixed;\n"
        "            border-spacing: 20px;\n"
        "        }\n"
        "        button {\n"
        "            font-size: 24px;\n"
        "            color: white;\n"
        "            background-color: #1a73e8;\n"
        "            border: none;\n"
        "            border-radius: 50%;\n"
        "            width: 70px;\n"
        "            height: 70px;\n"
        "            display: flex;\n"
        "            justify-content: center;\n"
        "            align-items: center;\n"
        "            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n"
        "            transition: background-color 0.3s, transform 0.2s;\n"
        "        }\n"
        "        button:active {\n"
        "            background-color: #0b5ed7;\n"
        "            transform: scale(0.95);\n"
        "        }\n"
        "        button i {\n"
        "            font-size: 28px;\n"
        "        }\n"
        "        td {\n"
        "            text-align: center;\n"
        "        }\n"
        "        img {\n"
        "            width: 100%;\n"
        "            border-radius: 10px;\n"
        "            box-shadow: 0 4px 8px rgba(0,0,0,0.1);\n"
        "        }\n"
        "    </style>\n"
        "    <script>\n"
        "        function sendRequest(action) {\n"
        "            var xhttp = new XMLHttpRequest();\n"
        "            xhttp.onreadystatechange = function () {\n"
        "                if (this.readyState == 4 && this.status == 200) {\n"
        "                    console.log(\"Respuesta del servidor:\", this.responseText);\n"
        "                }\n"
        "            };\n"
        "            xhttp.open('GET', action, true);\n"
        "            xhttp.send();\n"
        "        }\n"
        "    </script>\n"
        "</head>\n"
        "<body>\n"
        "    <h1>Control Rover</h1>\n"
        "    <table id=\"mainTable\">\n"
        "        <tr>\n"
        "            <td></td>\n"
        "            <td>\n"
        "                <button ontouchstart=\"sendRequest('/AVANZAR')\" ontouchend=\"sendRequest('/PARAR')\">\n"
        "                    <i class=\"fas fa-arrow-up\"></i>\n"
        "                </button>\n"
        "            </td>\n"
        "            <td></td>\n"
        "        </tr>\n"
        "        <tr>\n"
        "            <td>\n"
        "                <button ontouchstart=\"sendRequest('/GIRO_IZQUIERDA')\" ontouchend=\"sendRequest('/PARAR')\">\n"
        "                    <i class=\"fas fa-arrow-left\"></i>\n"
        "                </button>\n"
        "            </td>\n"
        "            <td>\n"
        "                <button ontouchstart=\"sendRequest('/PARAR')\" ontouchend=\"sendRequest('/PARAR')\">\n"
        "                    <i class=\"fa-solid fa-stop\"></i>\n"
        "                </button>\n"
        "            </td>\n"
        "            <td>\n"
        "                <button ontouchstart=\"sendRequest('/GIRO_DERECHA')\" ontouchend=\"sendRequest('/PARAR')\">\n"
        "                    <i class=\"fas fa-arrow-right\"></i>\n"
        "                </button>\n"
        "            </td>\n"
        "        </tr>\n"
        "        <tr>\n"
        "            <td></td>\n"
        "            <td>\n"
        "                <button ontouchstart=\"sendRequest('/RETROCEDER')\" ontouchend=\"sendRequest('/PARAR')\">\n"
        "                    <i class=\"fas fa-arrow-down\"></i>\n"
        "                </button>\n"
        "            </td>\n"
        "            <td></td>\n"
        "        </tr>\n"
        "    </table>\n"
        "</body>\n"
    "</html>\n";

    return app;
}
