#include "ControladorWeb.h"

ControladorWeb::ControladorWeb()=default;

String ControladorWeb::getWebApp(){
    String app = 
    "<!DOCTYPE html>" 
    "<html lang=\"es\">"
        "<head>"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
            "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">"
            "<style>"
                "body {"
                    "padding: 20px;"
                    "font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
                    "background-color: #f0f0f0;"
                    "color: #333;"
                    "text-align: center;"
                "}"
                "h1 {"
                    "color: #1a73e8;"
                    "font-size: 36px;"
                    "margin-bottom: 30px;"
                "}"
                "#mainTable {"
                    "width: 100%;"
                    "max-width: 400px;"
                    "margin: auto;"
                    "table-layout: fixed;"
                    "border-spacing: 20px;"
                "}"
                "button {"
                    "font-size: 24px;"
                    "color: white;"
                    "background-color: #1a73e8;"
                    "border: none;"
                    "border-radius: 50%;"
                    "width: 70px;"
                    "height: 70px;"
                    "display: flex;"
                    "justify-content: center;"
                    "align-items: center;"
                    "box-shadow: 0 4px 8px rgba(0,0,0,0.1);"
                    "transition: background-color 0.3s, transform 0.2s;"
                "}"
                "button:active {"
                    "background-color: #0b5ed7;"
                    "transform: scale(0.95);"
                "}"
                "button i {"
                    "font-size: 28px;"
                "}"
                "td {"
                    "text-align: center;"
                "}"
                "img {"
                    "width: 100%;"
                    "border-radius: 10px;"
                    "box-shadow: 0 4px 8px rgba(0,0,0,0.1);"
                "}"
            "</style>"
            "<script>"
                "function sendRequest(action) {"
                    "var xhttp = new XMLHttpRequest();"
                    "xhttp.onreadystatechange = function () {"
                    "if (this.readyState == 4 && this.status == 200) {"
                            "console.log(\"Respuesta del servidor:\", this.responseText);"
                        "}"
                    "};"
                    "xhttp.open('GET', action, true);"
                    "xhttp.send();"
                "}"
            "</script>"
        "</head>"

        "<body>"
            "<h1>Control Rover</h1>"

            "<table id=\"mainTable\">"
                "<tr>"
                    "<td></td>"
                    "<td>"
                        "<button ontouchstart=\"sendRequest('/AVANZAR')\" ontouchend=\"sendRequest('/PARAR')\">"
                            "&#9650;"
                        "</button>"
                    "</td>"
                    "<td></td>"
                "</tr>"
                "<tr>"
                    "<td>"
                        "<button ontouchstart=\"sendRequest('/GIRO_IZQUIERDA')\" ontouchend=\"sendRequest('/PARAR')\">"
                            "&#9668;"
                        "</button>"
                    "</td>"
                    "<td>"
                        "<button ontouchstart=\"sendRequest('/PARAR')\" ontouchend=\"sendRequest('/PARAR')\">"
                            "&#9634;"
                        "</button>"
                    "</td>"
                    "<td>"
                        "<button ontouchstart=\"sendRequest('/GIRO_DERECHA')\" ontouchend=\"sendRequest('/PARAR')\">"
                            "&#9658;"
                        "</button>"
                    "</td>"
                "</tr>"
                "<tr>"
                    "<td></td>"
                    "<td>"
                        "<button ontouchstart=\"sendRequest('/RETROCEDER')\" ontouchend=\"sendRequest('/PARAR')\">"
                            "&#9660;"
                        "</button>"
                    "</td>"
                    "<td></td>"
                "</tr>"
            "</table>"
        "</body>"
    "</html>";

    return app;
}
